[package]
name = "collider"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const-fnv1a-hash = "1.1.0"
dashmap = "5.5.3"
#ouroboros = "0.15.6"
